name: coinslib
description: A dart cryptocurrency library for Flutter, primarily build for Peercoin. BIP32, BIP39, P2PKH, bech32 integration.
version: 3.1.1
homepage: https://github.com/Vesta-wallet/coinslib
publish_to: https://pub.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bip39: ^1.0.6
  pointycastle: ^3.5.2
  hex: ^0.2.0
  bs58check: ^1.0.2
  meta: ^1.3.0
  collection: ^1.15.0

dev_dependencies:
  test: ^1.17.5
